### ISSUE TITLE
Structure du talk

### ISSUE THREAD

**Issue by julien-topcu** [openwhyd/openwhyd-solo#7]
# Déroulé du talk

## 0. Prérequis

Liens de référence:

* [Slides](https://slides.com/d/8VfoWr4/live)
* [Speaker view](https://slides.com/d/8VfoWr4/speaker/wwxWqpE)

Étapes de préparation pré-live-coding:

- Mettre VSCode en thème "fond clair".

- Installer [Snippet - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=devonray.snippet) pour VSCode.

- Créer snippet "`basic functional test`" avec [Snippet - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=devonray.snippet):

    <details>
      <summary>contenu du snippet</summary>
    
    ```js
    // @ts-check
    
    // run with: $ npx mocha test/functional/createPlaylist.functional.tests.js

    const assert = require('assert');
    const { createPlaylist } = require('../../app/domain/features');
    
    describe('playlist', () => {
      it('should be created by a user without playlist', async () => {
        const playlistName = 'summer mega mix 2022';
        const playlist = await createPlaylist('userWithoutPlaylist', playlistName);
        assert.equal(playlist.id, 0);
        assert.equal(playlist.name, playlistName);
      });
    
      it('should be created by a user with playlist', async () => {
        const playlistName = 'summer mega mix 2023';
        const playlist = await createPlaylist('userWithPlaylist', playlistName);
        assert.equal(playlist.id, 1);
        assert.equal(playlist.name, playlistName);
      });
    });
    ```
    </details>

- Préparer l'environnement de live coding, dans le terminal de VSCode:

    ```sh
    nvm use 
    npm install
    git checkout migration-start # ancienne version: migration-start-devoxx-2022
    docker compose up -d mongo
    . ./env-vars-testing.sh 
    export MONGODB_PORT=27117 
    npm run test-reset
    ```

## 1. Faire une démo d'OpenWhyd

**Adrien**

* La démo
* Décrire le problème : Les contributeurs ont lâché l'affaire car trop fragile et trop difficile à comprendre
* Survol de la code base :
  - Partir de Application.js
  - préciser que: pas de typage
  - parler du framework maison => fichier `app.route`, notamment les `api` --> `subdir` --> `controllers/api/post.js` --> fonction intéressante: insertion d'un morceau de musique. (post Controller sur la méthode `insert`)

Objectifs:
* Permettre à quelqu'un qui n'a pas d'expérience sur la code base d'openWhyd d'être autonome dans la correction de bugs.
* Le but étant de maintenir l'existant, on veut améliorer sur place ! On ne veut pas faire une fuite en avant, en créant un module from scratch qui paraitrait plus simple à faire mais qui rajouterait de la complexité de maintenance sur le legacy 

Donc => **Migration in situ**

## 2. Préparation du terrain opératoire: Biopsies Clean Codiennes

**But :** Y voir plus claire sur la code base 
**But caché (intention) :** Montrer la fragilité de la code base 

1. Expliquer que l'on vise de migrer l'action `insert` de `controllers/api/post`
1. Exécuter les tests d'intégration pour montrer qu'on en a :

```bash
npm run test:integration:post # avant, on lançait le serveur, puis: $ npm run test:integration
```
1. Changer dans `controllers/api/post`, `p` puis `uId` `uNm` de l'objet `q` dans `insert`. Et expliquer qu'on est en train de changer la structure en base de données.
3. ~~(redémarrer serveur puis)~~ Réexécuter les tests d'intégration et montrer que les messages d'erreurs ne permettent pas de voir ce qu'on a cassé

## 3. Ajout des approval tests

```bash
git checkout migration-start-with-approval-tests
npm install
```
1. Expliquer le principe des Approval tests, théorie + pratique.
1. Montrer un fichier d'approval de `When posting a track`
1. Ouvrir `approval.tests.js` et expliquer le test correspondant
1. Lancer le test :
```bash
npm run test:approval
```
1. Montrer dans les logs que l'on a un diff des approvals.
1. Supprimer la modification de userName et userId

## 4. Amener plus de lisibilité dans le code

**Lisibilité** 

Adrien: 
1. Survol de `insert` jusqu'à `process playlist` en expliquant le code
2. Montrer que `insert` a beaucoup de responsabilité => décider que la partie `createPlaylist` est déjà un scope suffisant à refactorer

Jordan:
1. ~~Extraction de `extractPlaylistRequest`~~
1. Passage du bloc try-catch en pure fonction
1. `postRequest.pl = extractPlaylistRequest(...)` et dire que ça pourrait être fait directement à l'initialisation de `postQuery`.
1. Remplacer l'initialisation à `undefined` par `extractPlaylistRequest(...)`
1. Extraction `needToCreatePlaylist` dans le if
1. Comment rendre la séquentialité de `createPlaylist` plus explicite ?

Adrien:
1. Wrapper dans une Promise `createPlaylist()`
2. Virer le `actualInsert()` superflu

**Diagnostic**
- Julien : Mais il fait quoi ce `createPlaylist` ?
- Adrien : Présente `userModel.createPlaylist()`
- Jordan & Julien s'étonnent et commentent du couplage du métier dans la couche de persistence

## 5. Modéliser le domaine

1. Créer le répertoire `domain`
2. Créer le contrat d'entrée du domaine via l'`api`. Le domaine doit dépendre que des objets du domaine, mais il n'y pas de typage fort en JS. 
  - Julien : On peut migrer TypeScript ?
  - Adrien : Trop compliqué mais y'a un autre moyen... Tu veux quoi comme types ? 
4. Création du type `CreatePlaylist` dans `api.ts`
5.  Création du type `Playlist`dans `types.ts` 
  - Julien : Mais du coup c'est du TypeScript, comment on va raccrocher les wagon sans migrer de langage ? 
  - Adrien : Avec la JSDoc
6. Refactorer l'appel de la `Promise(createPlaylist)` pour bien détourer la déclaration de la fonction `createPlaylist`
  ```javascript
const createPlaylist = (userId, playlistName) =>
        new Promise((resolve) =>
          userModel.createPlaylist(userId, playlistName, resolve)
);
```
7. Appliquer le type `CreatePlaylist` via JSDoc puis activer la vérification avec `ts-check`
8. Montrer que l'on bénéficie du typage dans vscode via l'autocomplétion sur `playlist` et les warnings de "compilation" si on fait un `playlist.toto`
9. Extract de `createPlaylist` dans `features.js` dans le domaine.
10. Appliquer le `ts-check` dans `features`
11. Lancer les approval tests

## 6. Extraire la logique métier de la couche de persistence

1. Remontrer le code de `userModel.createPlaylist()` pour caractériser le métier qu'on veut migrer.
1. ⚠️ **Créer un test fonctionnel** (ex: `test/functional/playlist.functional.test.js`) pour figer les comportements que l'on a compris et expliquer qu'on ne s'appuie pas sur les Approvals, car le domaine est testé en isolation pure.
1. Appliquer le [snippet](https://github.com/openwhyd/openwhyd-solo/issues/7#issuecomment-1099953118) `basic functional test` (clic droit + "insert snippet") et expliquer les tests
1. Supprimer la dépendance `userModel` dans `features.createPlaylist()` en la commentant
1. Résumer le code de `userModel.createPlaylist()` et écrire un "algo" dans `features`
```javascript
  await fetch()
  playlist = {
    id:
    name: 
  }
  await save()
  return playlist
```
6. Créer `spi.ts` 
7. Expliquer que les playlists sont stockées dans les utilisateurs, ce qui nécessite de créer un type `UserRepository`.
8. Ajouter une fonction `getUserById` qui retourne une Promise de User
9. Définir User dans `types.ts`
10. `features a maintenant besoin d'une instance de UserRepository. Comme on ne veut pas se coupler avec le repository, on crée une factory `createFeatures` pour d'injecter une instance.
12. Typer le paramètre `userRepository` de la factory
13. Appeler `userRepository.getUserbyId` dans `createPlaylist`
14. Retourner dans `userModel` et expliquer la logique de création d'un id de playlist, la copier-coller dans features et la nettoyer.
15. Julien à Adrien : est-ce qu'on doit sauvegarder tout le user pour sauvegarder une playlist ?
16. Définir une fonction `insertPlaylist` dans la SPI dans le `UserRepository`
17. L'appeler dans `features`
18. Replugguer dans le test fonctionnel via `createFeatures`
19. Expliquer la nécessité de créer un Stub de UserRepository
20. Créer le stub `userRepository` et la typer avec la SPI. Générer le squelette au moyen de l'IDE.
21. Créer une base d'utilisateurs dans le test pour initier le repository en reprenant les ids de user dans les tests fonctionnels
22. Implémenter les fonctions du Stubs
23. Enrichir les tests pour vérifier la persistance de la playlist
```javascript
    //premier test
    assert.deepEqual(users[0].playlists, [playlist]);
   //deuxieme test
    assert.deepEqual(users[1].playlists[1], playlist);
```
23. Faire passer les tests (`$ npx mocha test/functional/playlist.functional.test.js`)

## 7. Recabler le domaine avec la persistance

1. Créer un répertoire `infrastructure` avec `UserCollection.js`
2. Typer `UserCollection` avec la SPI et générer le squelette
3. Retourner dans le controller et rebinder le domain avec une instance de `UserCollection`
4. Exécution des tests approvals pour vérifier que le câblage fonctionne
5. Implémenter `UserCollection.getUserById()`
6. Lancer les approvals montrer que ça casse à cause d'un problème de length sur les playlists. Expliquer la différence de modélisation entre la base et le domaine (playlists vs pl). 
7. Définir `UserDocument` dans `infrastructure/type.ts`, typer le retour de la requête mongo dans `getUserbyId` et tenter de retourner le `userDocument`.
8. Créer la fonction de mapping `mapToUser` et expliquer le rôle de l'anti-corruption layer
9. Relancer les tests d'approval pour montrer que le problème n'est plus là
10. Implémenter `insertPlaylist`
12. Montrer que les tests d'approval ne fonctionnent toujours pas à cause de l'inconsistance des données en base (prefs, mid...).

Jordan reprend la main du copilote.
- Jordan : Où est-ce qu'on fait ça ? 
- Adrien montre d'où ça vient via le `fetch` et le `save` dans `userModel`
- Montrer que la migration de données est faite de manière implicite et n'est pas très robuste (s'il n'y a jamais de save après un save).

13. Appliquer la migration de données
```bash
git cherry-pick migrate-db # --> commit: 96d94f5ee3e5d4488615ca054a45b34c8e742a9a
```
Si le cherry-pick ne passe pas, vider l'index de git
14. Relancer les approvals

## 8. Découplage du controller

1. Commencer par le controller `post` en expliquant qu'on sort du fichier les instanciations. Commenter les require de `features` et `userCollection`
2. Faire passer `features` à la stack d'appel de `insert` jusqu'à `Application.js`
3. Ne pas oublier `subdir.js` en montrant `app.route`
4. Déplacer la création des objets dans `attachLegacyRoutesFromFile`
5. Relancer les tests d'approval et montrer que ça fonctionne

## 9. Décommisionnement des Approval tests (optionnel)

```bash
git checkout main
```
Aller dans les tests d'intégration de post et de l'infra mongo

-----
TODO:
- [ ] Voir comment définir les types en JSDoc de manière globale pour éviter les imports
-----

**Comment by julien-topcu** [comment]
## Point du 10/02/2022

### choix / décisions

- refactoring in-place: on modifie le code existant
- partir du principe que ça fair un bail que les serveurs web ne retournent plus d'HTML => on fix une API qui retourne du JSON (pas de présentation)
- focus sur une feature avec use case d'écriture/modification (ex: ajouter un morceau à son profil openwhyd: https://github.com/openwhyd/openwhyd/blob/master/test/integration/post.api.tests.js)

### cas typiques qu'on aimerait couvrir

- faire émerger le domaine depuis une codebase legacy
- couplage métier + technique
- code metier entre controlleurs et persitance, à séparer
- transitionner progressivement de JS à TS
- "poison pill" `pl.id == 'create'` (https://github.com/openwhyd/openwhyd/blob/master/test/integration/post.api.tests.js#L47) => cas à traiter par adaptateur, pour pas que `create` soit transmis au domaine
- manque d'IOC => introduire Nest ?

### TODO

- Adrien fournit une cartographie rapide des fichiers principaux à refacto
- Adrien fait le ménage dans openwhyd => garder seulement:
    - features "post track", "profile" et "playlist"
    - tests api + cypress correspondants
- Voir comment on insère du TypeScript dans cette codebase JS

**Comment by julien-topcu** [comment]
## STRATÉGIE DE MIGRATION:

- Mesure / Visualisation du coverage sur la feature à refacto:
    - Test E2E (GUI)
    - Test d'integration (API / Controller)

- Analyse du coverage, pour mettre en évidence les cas fonctionnels non couvert

- Analyse des tests de plus haut niveau pour voir si des usecases serait plus explicite à ce niveau là

- Remboursement de la couverture fonctionnelle:
    - Analyse les usecases couvert par les tests E2E / pour les redescendre potentiellement vers l'intégration
    - Exploration fonctionnelle pour re-comprendre, les critères d'acceptance manquant
    - Ecrire des tests au niveau intégration (controller)

- Inversion de controle entre la persistence et le controller /Rendre explicite le DTO coté base de donnée
    - Approval tests (DUMPDB MONGO):
        - https://github.com/approvals/Approvals.NodeJS#approvalsverifyasjson
    - Objectif: Controller <- Persistence (Mapping -> créer DTO dédiée (Voir pour l'introduction de typescript pour modeliser les types)) 

- Introduction de la couche domaine:
    - Aller plus loin avec l'inversion entre le controller et le domaine
        - Objectif: Controller -> Domaine <- Persistence
    - Définition du modele métier / ACL -> Mapping
        - Objectif: Controller(DTO / Mapping(ACL) -> Domaine(Modele dedié) <- Persistence

- Constat -> Modele métier actuel est anémique:
    - Remonter la logique métier de la persistence vers le domaine
    - Pousser la loguque métier du controller vers le domaine

- Introduction des tests de critére d'acceptance en isolation (TDD avec l'étape précèdent)

- Introduction des tests d'intégration vis a vis de notre persistence

**Comment by julien-topcu** [comment]
# Remboursement de la couverture fonctionnelle - Etapes

## Execution de test E2E

1. lancement

```sh
docker-compose up -d
open http://localhost:8080
```

2. login avec "admin" / "admin"
3. poster une track en collant une URL (ex: https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3) dans la barre recherche, puis la retrouver sur son profil openwhyd
4. ouvrir chrome dev tools
5. cliquer sur le "edit" de la track, changer le nom, valider
6. récupérer la requete HTTP emise pour éditer le titre ("copy as node.js fetch")
7. coller dans `test/integration/post.api.tests.js`, puis finir d'écrire le test => https://gitlab.com/shodo.io/public/hexagonal-architecture-nodejs-migration/-/commit/08bcc1ac83e37cefc54efe1227e4f2d6e60e5689
8. execution du test:

- dans un premier terminal:
```sh
. ./env-vars-testing.sh
export MONGODB_PORT=27117
export MONGODB_DATABASE=openwhyd_test
npm start
```

- dans un second terminal:
```sh
. ./env-vars-testing.sh
export MONGODB_PORT=27117
export MONGODB_DATABASE=openwhyd_test
npm run test-reset && npm run test:integration
```

## Next steps / TODO

- [x] Jordan & Adrien: fournir une liste de scenarios à écrire sous forme de tests d'intégration API
- [x] Julien: implémenter certain de ces tests dans `test/integration/post.api.tests.js` (cf TODOs dans ce fichier)
- [x] Adrien: fournir outil de dump MongoDB pour approval tests, si possible compatible avec https://github.com/approvals/Approvals.NodeJS
- [x] Jordan: automatiser la procédure d'execution des tests de `test/integration/post.api.tests.js`

**Comment by julien-topcu** [comment]
Montrer lors de la conf l'intérêt de faire des tests FIRST !

Repartir du test `should re-add a track into a new playlist` et montrer que son introduction fait péter une demi-douzaine d'autres tests car ils sont liés entre eux.

**Comment by JKratus** [comment]
Montrer l'évolution de la couverture du code liée aux fonctionnalités autour du concept de post, après le remboursement de la dette (test de controller post)

- dans un terminal:

```
docker-compose up -d mongo # starts mongo on port 27117
source ./env-vars-testing-local.sh
npm run test:integration:legacy-post:cov
```

- puis, dans un terminal séparé:

```
source ./env-vars-testing-local.sh
npm run test:integration:post:cov 
```

Les 2 commandes produisent un rapport qui peuvent être comparé

**Comment by JKratus** [comment]
Pour s'assurer d'être iso par rapport à la persistence d'un post, lancer les tests avec une approche approval testing basé sur  des dumps de la db

```
$ docker-compose up -d mongo
$ npm run -s test:approval:coverage
```

(les tests approval lancent le serveur et nettoient la DB programmatiquement)

**Comment by JKratus** [comment]
Pour visualiser directement le coverage dans vscode:
 - Installer Gutter for vscode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
 - Gutter se base sur le fichier coverage/lcov.info
 - Les commandes npm run test:integration:post:cov et npm run -s test:approval:coverage supprime le repertoire coverage pour avoir la couverture uniquement de la partie souhaitée.
 - Un fois un coverage généré, cliqué sur la pastille 'Watch' de vscode
 
![Screenshot 2022-03-08 at 12 38 15](https://user-images.githubusercontent.com/7414857/157231177-09211c87-747f-4e61-9b14-b75205b3aee7.png)
 - Le coverage s'affiche directement sur les fichiers dans l'IDE

**Comment by adrienjoly** [comment]
## 11 mars 

### Rappel de strat

1. virer le dead code + solidifier calcul de coverage
2. inverser dependance entre controleur et persistence
3. faire emerger le domaine

### TODO

- [ ] que faire du `src` ? (decision que c'est du dead code mais snapshoté dans les tests approval)
- [ ] ajouter couverture pour `img`
- [x] passer en await l'appel à `createPlaylist`, pour rendre plus lisibles la séquentialité et le retour de fonction => https://github.com/openwhyd/openwhyd-solo/pull/13/files#diff-db419e2f985ae41f450c2e0c2589debe9b177a41d6fc3c26f23c648adf4e1c5eR114

### Modélisation domaine

Jordan nous présente la ré-application de ce qu'on avait montré en live-stream:
- en fait, User est un agrégat de Playlists

### Elements de story-telling

1. reproduire rapidement ce qui s'est passé pendant le live => aller dans le mur, conclusion: need tests, moar coverage
1. ajouter des tests => surprise: découverte de side effects entre tests (violation de FIRST) => besoin de structure sûre pour nos prochains tests
    - [x] compute la couverture totale: approval + integration (pas forcément à montrer)
1. grace au coverage, on se rend compte qu'il y a pas mal de use cases couverts par fonction, et pas mal de lignes non couvertes
     - charge cognitive: on collapse les parties du code qui sont pas appelées
    - [x] clean code: renommer les params, extraction de fonctions, fonctions pures, pour améliorer lisibilité
    - en cas de test échoué, lancer seulement un type de test, sans coverage (pour pas niquer les numéros de ligne)
    - [x] => en CI, envoyer la coverage totale de `npm run test:post:coverage` sur codacy 
     - [x] montrer que une partie de `createPlaylist` n'est pas couverte (cf https://app.codacy.com/gh/openwhyd/openwhyd/file/68022651853/coverage?bid=17325385&fileBranchId=17325385) => écriture d'un test integration (à montrer en live)

1. on choisit de commencer par injecter `createPlaylist` (sous forme de domaine service) car il est deja relativement bien isolé, mais aussi pour avancer vers le retrait du poison pill `pl.id=="create"`
    - [x] wip: https://github.com/openwhyd/openwhyd-solo/pull/14
1. soit on va vers typescript, soit on continue d'extraire le domaine.

### Topo sur sessions effectuées jusque là

- 10/02 soir: discussion / propositions / planification => https://gitlab.com/shodo.io/public/hexagonal-architecture-nodejs-migration/-/issues/1
- 16/02 matin: première tentative de refacto, en stream live sur Twitch
- 25/02 matin: proposition de stratégie avec remboursement de tests => https://gitlab.com/shodo.io/public/hexagonal-architecture-nodejs-migration/-/issues/1#note_855177045,  puis déplacement de gitlab vers github => https://github.com/openwhyd/openwhyd-solo (pour réutilisation des workflows de CI)
- 28/02 aprem: écriture de tests
- 7/03 matin: écriture de tests (2)
- 11/03 matin: séance de refacto en mob, en physique => PR [refactor: Clean code](https://github.com/openwhyd/openwhyd-solo/pull/13) + branche [refactor: extract domain by adrienjoly · Pull Request #14 · openwhyd/openwhyd-solo](https://github.com/openwhyd/openwhyd-solo/pull/14)
- 23/03 matin: cf https://github.com/openwhyd/openwhyd-solo/issues/7#issuecomment-1076207196, Jordan et Julien se sont retrouvé au SHODO HQ, Adrien était en distanciel
- 25/03 matin: Adrien a simplifié l'implem du repository/adapter, cf https://github.com/openwhyd/openwhyd-solo/pull/18 (jour commu au lieu de destaff contenu, suite à l'impossibilité d'aller au Froiminaire)
- Mardi 29/03: Julien et Adrien vont passer la journée à construire le déroullement du talk sous forme de commits. (cf https://github.com/openwhyd/openwhyd-solo/issues/7#issuecomment-1081723718)
- Jeudi 7/04 aprem: Julien et Adrien vont terminer le déroullé
- Vendredi 8/04 journée: répétitions entre nous
- Mercredi 13/04: répétition générale au SHODAY
- Mercredi 20/04: talk donné à Devoxx

**Comment by adrienjoly** [comment]
## Matin du mercredi 23 mars

- Julien a présenté les étapes d'extraction du domaine depuis le code de `createPlaylist` => étranglement progressive du legacy, de gauche (APIs) à droite (mongodb)
- On est d'accord pour dire que le scope du talk est cet etranglement du use case "creation de playlist lors d'un post de track"
- on va prétendre qu'on a executé une migration de données (cf https://github.com/openwhyd/openwhyd-solo/pull/17#issue-1169492097)
  - à terme, notre implem de repository pourra appeler directement mongodb
  - [x] Adrien: ajouter les champs manquants aux données insérées dans nos tests
  - [x] virer le `fetchUserById()` de `UserCollection.insertPlaylist()` (cf code commenté)
  - [x] virer aussi la dépendance vers `models/users` en utilisant le driver mongo directement dans `getUserById`
  - [x] puis update les snapshots
- prochaine séance à prévoir: 1 journée pour construire le cheminement du live coding sous forme de commits

**Comment by adrienjoly** [comment]
## Mardi 29 Mars (journée)

- objectif de la séance: définir le déroulé du talk => écrire les commits dans une branche, avec annotations de ce qu'on devra dire/présenter le jour J (sous forme de commentaires GitHub dans une PR associée à cette même branche)

### Matin
 
- Julien a complété la description de ce ticket pour récapituler les grandes étapes
- on a décidé de partir des tests approval => création du tag [migration-start-with-approval-tests](https://github.com/openwhyd/openwhyd-solo/releases/tag/migration-start-with-approval-tests)
- pendant la pause dej, Adrien a proposé de compléter ces approval tests pour qu'ils couvrent aussi les réponses de l'API
    ![image](https://user-images.githubusercontent.com/531781/160607914-174864f8-dbcb-4533-9c42-b0904ecb77a1.png)

### Aprem

- on a complété la branche de déroulé (=> https://github.com/openwhyd/openwhyd-solo/pull/19) jusqu'à l'étape "6. Extraire la logique métier de la couche de persistence"
- on a décidé de décaler l'injection de dépendances à la fin, pour réduire la charge cognitive du public pendant la phase d'extraction de logique métier => ça a pris plus de temps que prévu => on pose notre Jeudi après midi de la semaine prochaine pour finir ça avant la journée de répétition du Vendredi 8
- il ne reste plus qu'à finir le déroulé (commits) pour les parties "7. Injection de dépendance", "8. Migration de donnée" et "9. Décommisionnement des Approval tests", en sachant que Jordan a proposé d'avancer de son côté sur l'écriture de tests DB pour la partie 9.

**Comment by adrienjoly** [comment]
## Jeudi 7 Avril (aprem, Julien + Adrien)

Objectif: finir déroullé ? (cf https://github.com/openwhyd/openwhyd-solo/pull/19)

- [x] 6. Extraire la logique métier de la couche de persistence
  - [x] Créer un test fonctionnel
  - [x] Définir une spi et une implémentation Stub pour les tests.
  - [x] Implémenter la logique métier dans le domaine.

- [x] 7. Injection de dépendance
  - [x] Inversion de dépendance entre le domaine et la persistence :
    - [x] Suppression de la dépendance vers userModel au profit de l'adaptateur Mongo  
    - [x] Migration de donnés, pour qu'on puisse s'appuyer sur nos tests approval
    - [x] Définir les structures de bases de donnée et faire l'anti-corruption layer
    - [x] Instancier le domaine et la persistance dans le controller.
  - [x] Injecter le domaine dans le controller à partir de l'Application (composition root)
    - [x] Supprimer la fonction createPlaylist de userModel

- [ ] ~~9~~ 8. Décommisionnement des Approval tests
  - [ ] Ajout des tests d'intégration de controller
  - [ ] Ajout du test de l'adaptateur Mongo

- [ ] corriger le bug d'incrementation d'id

- [ ] TODO: Réintégrer dans la branche migration les infrastructures permettant de simplifier le lancement les tests et le coverage
     - https://github.com/openwhyd/openwhyd-solo/commit/90163906221f2af5c24c6a5f35370820248e0634
     - https://github.com/openwhyd/openwhyd-solo/commit/9b3a385a19fad171f436fe492204be3f49def406
     - Toutes modifications faites dans le répertoire test de https://github.com/openwhyd/openwhyd-solo/pull/14/files

**Comment by adrienjoly** [comment]
## Vendredi 8 Avril

Répétition avec Julien et Jordan

=> branche [`migration-2022-04-08`](https://github.com/openwhyd/openwhyd-solo/compare/migration-2022-04-08)

**Comment by adrienjoly** [comment]
## Jeudi 13 Avril

Répétition pendant SHODAY.

=> branche: https://github.com/openwhyd/openwhyd-solo/tree/migration-2022-04-13-shoday

### Anti-sèche

- branche git à checkout pour l'ajout des approval tests: `migration-start-with-approval-tests`
- commit de la migration de données: [`ce3d2f4662b62693675c8866d0c3372fa166e424`](https://github.com/openwhyd/openwhyd-solo/commit/ce3d2f4662b62693675c8866d0c3372fa166e424) (à cherry-pick pendant le talk)

**Comment by adrienjoly** [comment]
## Vendredi 15 Avril

Je viens de créer deux snippets avec l'extension [Snippet - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=devonray.snippet):

![image](https://user-images.githubusercontent.com/531781/163544751-900c5f31-4387-42b0-8a8c-c86231d5bee6.png)

## TODO

- [x] revoir ensemble les slides, savoir qui dit quoi
- [x] préparer snippets 
- [x] créer une cheatsheet du déroullé (sous étapes)

=> branche: [migration-2022-04-15](https://github.com/openwhyd/openwhyd-solo/compare/migration-2022-04-15)

**Comment by adrienjoly** [comment]
Pour référence, voici:
- l'enregistrement video du talk à Devoxx dans lequel nous avons effectué la migration: [Architecturoplastie hexagonale d’un backend Node.js (Jordan Nourry, Adrien Joly, Julien Topçu) - YouTube](https://www.youtube.com/watch?v=r2XMwAUqZBA)
- les commits d'intégration de cette migration dans la codebase initiale d'Openwhyd, effectués lors du [SHODAY du 2022-05-09](https://github.com/openwhyd/openwhyd/issues/559): 
  - [fix(tests): Import test environment from openwhyd-solo](https://github.com/openwhyd/openwhyd/commit/1710bbeabce4c7ed0b991d13f24d858637513a06) (PR: [#560](https://github.com/openwhyd/openwhyd/pull/560))
  - [fix: Migrate playlist creation to Hexagonal Architecture](https://github.com/openwhyd/openwhyd/commit/9aff4ac0ad21cd1de2992cad9bc72a2eed7c1185) (PR: [#563](https://github.com/openwhyd/openwhyd/pull/563))

**Comment by adrienjoly** [comment]
Update suite à la répète de Lundi:

- j'ai remplacé le tag `migration-start` pour qu'il pointe vers l'unique commit de https://github.com/openwhyd/openwhyd-solo/pull/21 => les tests d'intégration de post api n'ont plus besoin qu'on lance le serveur d'openwhyd
- j'ai renommé l'ancien tag `migration-start` --> `migration-start-devoxx-2022`, au cas où
- j'ai simplifié la procédure de préparation du live coding + les mentions à `npm start` et `kill`, en accord avec ce changement

Note: je n'ai pas modifié le tag `checkout migration-start-with-approval-tests` car il me semble qu'on ne lance plus ces tests d'intégration après la migration. => on aura probablement envie de le faire, si jamais on trouve un moyen simple et fluide d'exécuter les nouveaux tests d'intégration (requêtes db via SPI) après la migration.

**Comment by adrienjoly** [comment]
Notes de 2ème répète:

- Julien: ne pas hésiter à sauter les slido, le jour J (à minima: le premier)
- Adrien: penser à présenter toute la logique de `insert`, y compris la partie sur les playlists
- Adrien: justifier le choix de focaliser sur `createPlaylist` par le fait que ça ne dépend de rien d'autre => scope réduit
- Julien & Adrien: pour rendre la phase de clean code plus rapide, ne pas extraire la constante `playlistRequest` (cf diff ci-dessous)
- Julien: ne pas hésiter à suivre les notes / process du live coding
- Adrien: retrouver rapidement les commandes pour runner les tests, et exploiter l'arbre git (checkout / cherry pick)
- Julien / idée pour slide de fin: être un poil plus "pratique" sur ce qu'a apporté nos modifs, concrètement
- Interactions: restons sur le vouvoiement; et si jamais on switch sans faire exprès, l'assumer explicitement !
- Interactions: Ne pas hésiter à exagérer les réactions et les vannes, pour divertir le public !

```diff
diff --git a/app/controllers/api/post.js b/app/controllers/api/post.js
index 3728376..e32f36d 100644
--- a/app/controllers/api/post.js
+++ b/app/controllers/api/post.js
@@ -63,6 +63,7 @@ exports.actions = {
       uId: httpParams.uId,
       uNm: httpParams.uNm,
       text: httpParams.text || '',
+      pl: extractPlaylistRequest(httpParams),
       // fields that will be ignored by rePost():
       name: httpParams.name,
       eId: httpParams.eId,
@@ -105,23 +106,18 @@ exports.actions = {
       }
     }
 
-    const playlistRequest = extractPlaylistRequest(httpParams);
-
-    if (needToCreatePlaylist(playlistRequest)) {
+    if (needToCreatePlaylist(postQuery.pl)) {
       const playlist = await features.createPlaylist(
         httpParams.uId,
-        playlistRequest.name
+        postQuery.pl.name
       );
       if (playlist) {
-        postQuery.pl = { id: playlist.id, name: playlistRequest.name };
+        postQuery.pl.id = playlist.id;
         // console.log('playlist was created', q.pl);
       }
     } else {
-      postQuery.pl = {
-        id: parseInt(playlistRequest.id),
-        name: playlistRequest.name,
-      };
-      if (isNaN(playlistRequest.id)) delete postQuery.pl; //q.pl = null;
+      postQuery.pl.id = parseInt(postQuery.pl.id);
+      if (isNaN(postQuery.pl.id)) delete postQuery.pl; //q.pl = null;
     }
 
     actualInsert();
```
